export const DEMO_PASSWORD = 'Kito-Demo-2026!';

export type SeedMember = {
  email: string;
  fullName: string;
  role: 'MEMBER' | 'TREASURER' | 'CHAPTER_LEAD' | 'ADMIN';
  chapterCode: string;
  brokerage: string;
  phone: string;
};

export const NAIROBI_MEMBERS: SeedMember[] = [
  {
    email: 'grace.wanjiru@kito.test',
    fullName: 'Grace Wanjiru',
    role: 'TREASURER',
    chapterCode: 'NBO',
    brokerage: 'Westlands Realty',
    phone: '+254711000001',
  },
  {
    email: 'daniel.otieno@kito.test',
    fullName: 'Daniel Otieno',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Lakeview Homes',
    phone: '+254711000002',
  },
  {
    email: 'amara.njeri@kito.test',
    fullName: 'Amara Njeri',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Ridgeway Partners',
    phone: '+254711000003',
  },
  {
    email: 'kevin.mwangi@kito.test',
    fullName: 'Kevin Mwangi',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Summit Estates',
    phone: '+254711000004',
  },
  {
    email: 'amina.hassan@kito.test',
    fullName: 'Amina Hassan',
    role: 'CHAPTER_LEAD',
    chapterCode: 'NBO',
    brokerage: 'Coastal & Capital',
    phone: '+254711000005',
  },
  {
    email: 'james.gitonga@kito.test',
    fullName: 'James Gitonga',
    role: 'ADMIN',
    chapterCode: 'NBO',
    brokerage: 'KITO Network',
    phone: '+254711000006',
  },
  {
    email: 'lucy.akinyi@kito.test',
    fullName: 'Lucy Akinyi',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Parklands Homes',
    phone: '+254711000007',
  },
  {
    email: 'brian.kiprotich@kito.test',
    fullName: 'Brian Kiprotich',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Rift Valley Realty',
    phone: '+254711000008',
  },
  {
    email: 'faith.chebet@kito.test',
    fullName: 'Faith Chebet',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Hillcrest Agency',
    phone: '+254711000009',
  },
  {
    email: 'peter.kamau@kito.test',
    fullName: 'Peter Kamau',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Thika Road Homes',
    phone: '+254711000010',
  },
  {
    email: 'mercy.wambui@kito.test',
    fullName: 'Mercy Wambui',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Karen Estates',
    phone: '+254711000011',
  },
  {
    email: 'samuel.odiambo@kito.test',
    fullName: 'Samuel Odhiambo',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Nyali to Nairobi',
    phone: '+254711000012',
  },
  {
    email: 'esther.muthoni@kito.test',
    fullName: 'Esther Muthoni',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Langata Living',
    phone: '+254711000013',
  },
  {
    email: 'joseph.kipchoge@kito.test',
    fullName: 'Joseph Kipchoge',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Eldoret Link',
    phone: '+254711000014',
  },
  {
    email: 'anne.wanjiku@kito.test',
    fullName: 'Anne Wanjiku',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Kiambu Homes',
    phone: '+254711000015',
  },
  {
    email: 'david.otieno@kito.test',
    fullName: 'David Otieno',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Kisumu Desk Nairobi',
    phone: '+254711000016',
  },
  {
    email: 'catherine.njoroge@kito.test',
    fullName: 'Catherine Njoroge',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Upper Hill Partners',
    phone: '+254711000017',
  },
  {
    email: 'michael.barasa@kito.test',
    fullName: 'Michael Barasa',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Western Realty',
    phone: '+254711000018',
  },
  {
    email: 'joan.adhiambo@kito.test',
    fullName: 'Joan Adhiambo',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Breeze Properties',
    phone: '+254711000019',
  },
  {
    email: 'eric.mutua@kito.test',
    fullName: 'Eric Mutua',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Machakos Homes',
    phone: '+254711000020',
  },
  {
    email: 'sarah.cherono@kito.test',
    fullName: 'Sarah Cherono',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Kericho Estates',
    phone: '+254711000021',
  },
  {
    email: 'paul.mwangi@kito.test',
    fullName: 'Paul Mwangi',
    role: 'MEMBER',
    chapterCode: 'NBO',
    brokerage: 'Nyeri Link',
    phone: '+254711000022',
  },
];

export const OTHER_CHAPTER_LEADS: SeedMember[] = [
  {
    email: 'fatma.ali@kito.test',
    fullName: 'Fatma Ali',
    role: 'CHAPTER_LEAD',
    chapterCode: 'MSA',
    brokerage: 'Nyali Shores',
    phone: '+254722000001',
  },
  {
    email: 'tom.oduor@kito.test',
    fullName: 'Tom Oduor',
    role: 'CHAPTER_LEAD',
    chapterCode: 'KSM',
    brokerage: 'Winam Realty',
    phone: '+254733000001',
  },
  {
    email: 'rose.chepkemoi@kito.test',
    fullName: 'Rose Chepkemoi',
    role: 'CHAPTER_LEAD',
    chapterCode: 'NKR',
    brokerage: 'Menengai Homes',
    phone: '+254744000001',
  },
];
